SELECT a.product_code as PRODUCT_CODE,SUM(b.SALES_AMOUNT)*a.price as SALES
FROM PRODUCT as a
 INNER JOIN OFFLINE_SALE as b
 ON a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY a.product_id
ORDER BY SALES DESC,PRODUCT_CODE;
