

SELECT ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO 
WHERE ITEM_ID in
    (SELECT T.ITEM_ID
    FROM ITEM_INFO I
    JOIN ITEM_TREE T on (T.PARENT_ITEM_ID=I.ITEM_ID)
    WHERE I.RARITY = 'RARE')
ORDER BY ITEM_ID desc;