# SELECT B.TITLE,B.BOARD_ID,R.REPLY_ID,R.WRITER_ID,R.CONTENTS,CONCAT(YEAR(R.CREATED_DATE),'-',MONTH(R.CREATED_DATE),'-',DAY(R.CREATED_DATE)) as CREATED_DATE
SELECT B.TITLE,B.BOARD_ID,R.REPLY_ID,R.WRITER_ID,R.CONTENTS,DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD AS B
    INNER JOIN USED_GOODS_REPLY AS R
    ON B.BOARD_ID = R.BOARD_ID
WHERE MONTH(B.CREATED_DATE)=10 AND YEAR(B.CREATED_DATE)=2022
ORDER BY R.CREATED_DATE, B.TITLE