# -- 코드를 입력하세요
# SELECT CATEGORY,  SUM(SALES) AS TOTAL_SALES
# FROM BOOK_SALES S
# JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
# WHERE DATE_FORMAT(sales_date,'%c')='1' ;

SELECT CATEGORY,  SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES S
JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(sales_date,'%c')='1' 
GROUP BY CATEGORY
ORDER BY CATEGORY;